file_opener = "cursor"
model = "gpt-5.4"
model_reasoning_effort = "high"
suppress_unstable_features_warning = true
web_search = "live"

[features]
rmcp_client = true
skills = true
default_mode_request_user_input = true
js_repl = true
prevent_idle_sleep = true

[projects."/Users/nicktrombley/Code/acorn"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Downloads"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/chestnut"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/red-cliff-record"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/dotfiles"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/bee"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/acorn--dev-pinned"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/intents-redesign"]
trust_level = "trusted"

[projects."/Users/nicktrombley"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Code/guidance-studio"]
trust_level = "trusted"

[projects."/Users/nicktrombley/conductor/repos/trail-mix"]
trust_level = "trusted"

[projects."/Users/nicktrombley/Library/Application Support/com.conductor.app/bin"]
trust_level = "trusted"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--autoConnect"]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-used", "five-hour-limit", "weekly-limit"]
